# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Terminal 1
    init:  |
      npm install -g json
      python -m install scipy
      sudo pip3 install streamlit
      sudo pip3 install streamlit-autorefresh
      sudo pip3 install matplotlib
      sudo apt-get install libsndfile1
      sudo pip install librosa
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto status
      sudo pip3 install paho-mqtt
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      cd ..
  
    command: streamlit run Site_controlo.py
  - name: Terminal 2
    init:  |
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto status
      sudo pip3 install paho-mqtt
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      cd ..

    command: python Subscribe.py


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1883
    onOpen: ignore
  - port: 8501
    name: web app
    onOpen: open-browser
    visibility: public
